### ISSUE TITLE
An unexpected delay occurs when opening Yazi (:Yazi) when using tmux

### ISSUE THREAD

**Issue by itse4elhaam** [mikavilpas/yazi.nvim#603] opened 2024-12-08 07:37 UTC
![image](https://github.com/user-attachments/assets/95409008-fabd-4d56-a10e-f286ac9cb715)

**Comment by mikavilpas** [comment] 2024-12-08 07:44
Hi, are you still working on this issue? I currently see a still image but was expecting maybe a video and some explanation.

**Comment by itse4elhaam** [comment] 2024-12-08 07:51
Maybe I was not able to explain it well.

Expected Behaviour:

I run :Yazi and it should open Yazi in a floating window.

What Happens:

I run :Yazi and the screen stays blank for some time and then after a minute Yazi loads. Here is a better screenshot:

![image](https://github.com/user-attachments/assets/34980997-c7bf-4daf-a184-a633f35e5d71)

**Comment by mikavilpas** [comment] 2024-12-08 07:57
Are you on Windows by any chance? I'm thinking it's maybe related to your environment.

Can you try to reproduce it with a minimal configuration? That way we could learn a bit more about the issue.
https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md

For reference, here is the performance that I see in my own setup:

https://github.com/user-attachments/assets/2cd149e3-57e7-4459-81fa-2b26eb94a485

**Comment by mikavilpas** [comment] 2024-12-08 08:03
You could also try opening `:term` which opens a new terminal in neovim, and then running `yazi` there to see if it's also slow there. If you can, send me a video of you doing that. Maybe it's the best way to understand what it looks like 🙂

**Comment by mikavilpas** [comment] 2024-12-08 15:18
It looks like there is some delay in opening yazi.

- do you get the same delay outside of neovim, in your terminal?
- do you get this delay if you run `:term` in neovim, and then start yazi in that terminal?

**Comment by redbeardymcgee** [comment] 2024-12-08 15:26
I noted that I followed your instructions to the same result, as well as running `yazi` in a normal terminal.

**Comment by mikavilpas** [comment] 2024-12-08 15:39
If it's also slow when starting yazi outside of yazi.nvim in a terminal, it's most likely an issue with yazi. It might be that it needs to be addressed there.

But before opening an issue against yazi, it might be worth it to try https://github.com/sxyazi/yazi/releases/tag/v0.4.0 which was released about an hour ago. It may work better, and most likely fixing this issue should be done against the newest version anyway.

**Comment by itse4elhaam** [comment] 2024-12-08 15:47
Hey @mikavilpas Here is my configuration if you still need to try and reproduce the issue. And yes technically I am on windows but I am using WSL2 Ubuntu.

https://github.com/itse4elhaam/nvim-nvchad/tree/feat/yazi

Also, yes it does seem like an env related issue.

**Comment by itse4elhaam** [comment] 2024-12-08 15:51
@mikavilpas I think you can close this issue. The problem seems to occur when you try to open yazi in a Nvim integrated terminal.

Thanks for your support man!

**Comment by redbeardymcgee** [comment] 2024-12-08 16:01
> If it's also slow when starting yazi outside of yazi.nvim in a terminal, it's most likely an issue with yazi. It might be that it needs to be addressed there.
> 
> But before opening an issue against yazi, it might be worth it to try [sxyazi/yazi@`v0.4.0` (release)](https://github.com/sxyazi/yazi/releases/tag/v0.4.0) which was released about an hour ago. It may work better, and most likely fixing this issue should be done against the newest version anyway.

Hi, thanks for looking into this.

I'm already running 0.4.0, as I tested it for this issue and updated all my plugins.

![satty-2024-12-08_09:59:33](https://github.com/user-attachments/assets/5052e25a-1819-4959-b502-1d9caac5199a)

As stated in orange, I tried running it in a `:term` as per your instruction and the result was a slow buggy startup.

In red, I noted that the issue does not occur outside `nvim`.

Hope this clears everything up.

**Comment by mikavilpas** [comment] 2024-12-08 16:10
@redbeardymcgee instead of bisecting your config, can you try the following:

If you open yazi in the minimal reproduction setup (detailed in https://github.com/mikavilpas/yazi.nvim/blob/main/documentation/reproducing-issues.md), do you get the slow startup with yazi.nvim?

Also, do you get the slow startup in `:term`?

**Comment by redbeardymcgee** [comment] 2024-12-08 16:28
@mikavilpas I'm so sorry, but can I confirm that you've actually read my comments? I'm not sure how you don't see the answers to your questions. I'm worried that perhaps github is hiding them from you?

**Comment by redbeardymcgee** [comment] 2024-12-08 16:35
I have confirmed the issue exists even with the minima repro config.

<details>
<summary>Log</summary>

```
[2024-12-08 10:32:29] DEBUG YaziFloatingWindow opening (content_buffer: 3, win: 1002)
[2024-12-08 10:32:29] DEBUG Opening yazi with the command: (yazi '/home/rbm' --chooser-file /tmp/nvim.rbm/lNseAK/0 --client-id 877848368349440).
[2024-12-08 10:32:29] DEBUG Opening ya with the command: (ya sub rename,delete,trash,move,cd,hover,bulk), attempt 0
[2024-12-08 10:32:50] DEBUG ya stdout: 'cd,0,877848368349440,{"tab":1,"url":"/home/rbm"}
'
[2024-12-08 10:32:50] DEBUG Parsed events: { {
    id = "877848368349440",
    timestamp = "0",
    type = "cd",
    url = "/home/rbm"
  } }
[2024-12-08 10:32:50] DEBUG Changing the cwd from nil to /home/rbm
[2024-12-08 10:32:50] DEBUG ya stdout: 'hover,0,877848368349440,{"tab":1,"url":null}
'
[2024-12-08 10:32:50] DEBUG Parsed events: { {
    type = "hover",
    url = "",
    yazi_id = "877848368349440"
  } }
[2024-12-08 10:32:50] DEBUG Changing the last hovered_url to 
[2024-12-08 10:32:50] DEBUG Calculating the highlights for 0 buffers
[2024-12-08 10:32:50] DEBUG { "emitting", "YaziDDSHover", {
    type = "hover",
    url = "",
    yazi_id = "877848368349440"
  } }
[2024-12-08 10:32:50] DEBUG ya stdout: 'hover,0,877848368349440,{"tab":1,"url":"/home/rbm/Desktop"}
'
[2024-12-08 10:32:50] DEBUG Parsed events: { {
    type = "hover",
    url = "/home/rbm/Desktop",
    yazi_id = "877848368349440"
  } }
[2024-12-08 10:32:50] DEBUG Changing the last hovered_url to /home/rbm/Desktop
[2024-12-08 10:32:50] DEBUG Calculating the highlights for 0 buffers
[2024-12-08 10:32:50] DEBUG { "emitting", "YaziDDSHover", {
    type = "hover",
    url = "/home/rbm/Desktop",
    yazi_id = "877848368349440"
  } }
[2024-12-08 10:33:17] DEBUG Killing ya process
[2024-12-08 10:33:17] DEBUG Waiting for ya process to exit
[2024-12-08 10:33:17] DEBUG ya stdout: ''
[2024-12-08 10:33:17] DEBUG Parsed events: {}
[2024-12-08 10:33:17] DEBUG yazi process exited successfully with code: 0, selected_files {}, and events {}
[2024-12-08 10:33:17] DEBUG Resolved the last_directory to /home/rbm
[2024-12-08 10:33:17] DEBUG YaziFloatingWindow closing (content_buffer: 3, win: 1002)
```

</details>

**Comment by chenxin-yan** [comment] 2024-12-08 22:14
I encountered a similar issue on macOS with WezTerm inside a tmux session. I already migrated my configuration to Yazi 4.0.

**Comment by redbeardymcgee** [comment] 2024-12-09 02:16
Yazi 0.4.0 (60ed6c9 2024-12-08) fixed this issue for me. Thanks for your awesome repro config @mikavilpas, it really saved me a lot of time and complexity.

sxyazi/yazi#2015 indicates that WSL environments may still be affected, for any future readers who arrive here.

**Comment by mikavilpas** [comment] 2024-12-09 04:57
Awesome! I pinned this issue as I think it may be a common bug with the yazi version 0.4.0

**Comment by chenxin-yan** [comment] 2024-12-09 08:06
I can confirm that Yazi's latest commit fixed the issue.

**Comment by mikavilpas** [comment] 2024-12-09 08:21
Excellent work. I'll close this issue as the cause seems to be known and a fix is available in the nightly yazi.

**Closed by mikavilpas** 2024-12-09 08:21 UTC

**Comment by sxyazi** [comment] 2024-12-10 12:40
Released a new version with the fix https://github.com/sxyazi/yazi/releases/tag/v0.4.1 🎉

**Comment by mikavilpas** [comment] 2024-12-10 12:42
Very nice! Thanks again for a fast response 👍🏻

**Comment by kohane27** [comment] 2024-12-15 17:40
Thanks guys! I have this exact problem after updating to v0.4.0 and updating to v0.4.2 fixed this issue. Appreciate all the help and quick response!

**Comment by juanibiapina** [comment] 2024-12-28 19:19
I still have it in yazi 0.4.2, but only when using this plugin. it works normally with `:terminal yazi`

**Comment by mikavilpas** [comment] 2024-12-28 19:42
@juanibiapina try to pin down where it happens. You can try disabling half of your plugins/config and retrying until you find the cause, for example (binary search)

**Comment by juanibiapina** [comment] 2024-12-28 19:59
It's caused by [vim-projectionist](https://github.com/tpope/vim-projectionist) plus:
```
let g:projectionist_heuristics = {
      \  "*.gemspec" : {
      \  },
      \}
```
:scream:

**Comment by mikavilpas** [comment] 2024-12-28 20:10
Interesting! Could you open a new issue for this? I can take a look at it in the coming days.
